# Generated by Django 4.0.3 on 2022-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='defaultcover.jpg', null=True, upload_to='Files/pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.png', null=True, upload_to='Files/pics'),
        ),
    ]
