# Generated by Django 4.0.3 on 2022-04-09 19:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_profile_g_course_profile_p_course_profile_p_study_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='defaultcover.jpg', null=True, upload_to='Files/pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='Files/pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_as',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
