# Generated by Django 4.0.3 on 2022-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='g_course',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_course',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_study_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
