# Generated by Django 4.0.3 on 2022-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_post_like_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
