# Generated by Django 4.0.3 on 2022-04-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0011_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
