# Generated by Django 4.0.3 on 2022-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0014_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='count',
            field=models.IntegerField(blank=True, default=1, max_length=2000, null=True),
        ),
    ]
