# Generated by Django 4.0.3 on 2022-04-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0015_alter_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='count',
        ),
    ]
