# Generated by Django 4.0.3 on 2022-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0016_remove_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comm_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
