# Generated by Django 4.0.3 on 2022-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0017_post_comm_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comm_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
