# Generated by Django 4.0.3 on 2022-04-26 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialapp', '0018_alter_post_comm_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comm_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
