# Generated by Django 4.0.3 on 2022-04-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0020_profile_friends_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='status',
        ),
    ]
