# Generated by Django 4.0.3 on 2022-09-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0022_alter_friend_request_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
